### ISSUE TITLE
Option naming

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/in-range#6]
Is there a specific motivation for naming the options `start` and `end` instead of something more conventional like `min` and `max`?

```js
inRange(x, {min: 5, max: 10});
```

> Am researching [for implementing in ava](https://github.com/avajs/ava/discussions/3315)

// @sindresorhus

**Comment by sindresorhus** [comment]
A range has a start and end. See the Python range() function, for example.

**Comment by Richienb** [comment]
Thank you
